# Smart Tree Multi-Remote Configuration
# This file defines remote repositories and their purposes

remotes:
  github:
    url: git@github.com:8b-is/smart-tree.git
    alias: origin
    purpose: "Primary public repository - stable releases"
    push_tags: true
    push_releases: true
    default_branches:
      - main
      - release/*
    
  forgejo:
    url: git@g.8b.is:8b-is/smart-tree.git
    alias: forgejo
    purpose: "8b.is private instance - experimental features"
    push_tags: false
    push_releases: false
    default_branches:
      - main
      - experimental/*
      - quantum/*
      - feature/*
    temperature_threshold: 3  # Only sync when temp >= 3
    
  gitlab:
    url: git@gitlab.com:8b-is/smart-tree.git
    alias: gitlab
    purpose: "GitLab mirror - CI/CD and backup"
    push_tags: true
    push_releases: true
    default_branches:
      - main
      - stable/*
    temperature_threshold: 5  # Only sync when temp >= 5

# Sync strategies based on "temperature"
temperature_profiles:
  cold: # 0-2
    description: "Conservative - GitHub only, manual approval"
    remotes: [github]
    requires_confirmation: true
    
  cool: # 3-4
    description: "Careful - GitHub primary, Forgejo experimental"
    remotes: [github, forgejo]
    experimental_only_to: [forgejo]
    
  moderate: # 5-6
    description: "Balanced - All remotes, stable branches"
    remotes: [github, forgejo, gitlab]
    branch_filter: "^(main|stable|release).*"
    
  warm: # 7-8
    description: "Active - All remotes, all branches"
    remotes: [github, forgejo, gitlab]
    include_experimental: true
    
  hot: # 9-10
    description: "Aggressive - Force sync everywhere"
    remotes: [github, forgejo, gitlab]
    force_push: true
    sync_all_branches: true
    sync_all_tags: true

# Branch routing rules
branch_routing:
  # Experimental features go to Forgejo first
  - pattern: "^experimental/.*"
    remotes: [forgejo]
    exclusive: true
    
  # Quantum features can go to Forgejo and GitLab
  - pattern: "^quantum/.*"
    remotes: [forgejo, gitlab]
    
  # Security fixes go everywhere immediately
  - pattern: "^security/.*"
    remotes: [github, forgejo, gitlab]
    priority: high
    
  # Personal experiments stay on Forgejo
  - pattern: "^hue/.*"
    remotes: [forgejo]
    exclusive: true

# Tribal forks configuration
tribal_forks:
  - name: "smart-tree-quantum"
    remote: "quantum-fork"
    url: "git@g.8b.is:quantum-tribe/smart-tree.git"
    sync_strategy: "pull-only"
    description: "Quantum-focused fork with aggressive optimizations"
    
  - name: "smart-tree-minimal"
    remote: "minimal-fork"
    url: "git@g.8b.is:minimalist-tribe/smart-tree.git"
    sync_strategy: "cherry-pick"
    description: "Stripped-down version for embedded systems"

# Webhook notifications
notifications:
  forgejo:
    webhook: "https://g.8b.is/api/v1/repos/8b-is/smart-tree/hooks"
    events: ["push", "tag", "release"]
    
  discord:
    webhook: "${DISCORD_WEBHOOK_URL}"
    events: ["release", "security"]
    
  matrix:
    webhook: "https://matrix.8b.is/_matrix/client/r0/rooms/!smarttree:8b.is/send"
    events: ["experimental", "quantum"]

# Testing remotes (for selective pushes)
testing_remotes:
  - name: "ci-test"
    url: "git@ci.8b.is:testing/smart-tree.git"
    purpose: "Automated testing before public push"
    pre_push_checks:
      - "cargo test"
      - "cargo clippy"
      - "./scripts/manage.sh test"
      
  - name: "quantum-test"
    url: "git@quantum.8b.is:test/smart-tree.git"
    purpose: "Quantum feature testing"
    pre_push_checks:
      - "cargo test --features quantum"