[package]
name = "smart-edit-showcase"
version = "0.1.0"
edition = "2021"

[dependencies]
# These would be real dependencies in a real project
# jwt = "8.0"
# serde = { version = "1.0", features = ["derive"] }
# log = "0.4"
# metrics = "0.21"