# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SmartTree < Formula
  desc "A command line tool for exploring complex project structures"
  homepage "https://github.com/8b-is/smart-tree"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/8b-is/smart-tree/releases/download/v0.1.1/st-v0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "..."
    end
    if Hardware::CPU.intel?
      url "https://github.com/8b-is/smart-tree/releases/download/v0.1.1/st-v0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "..."
    end
  end

  def install
    bin.install "st"
  end

  test do
    system "#{bin}/st", "--version"
  end
end 