[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# Optional: For better cross-compilation support
[target.aarch64-unknown-linux-gnu.env]
CC = "aarch64-linux-gnu-gcc"
CXX = "aarch64-linux-gnu-g++"
AR = "aarch64-linux-gnu-ar"

# You can also add other targets if needed
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc" 